# Default values for gk_xml.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: alle-mail
namespace: alle-uat
TZ: Europe/Warsaw
node: "k102"
node_mail: "k141"
revisionHistoryLimit: 2

app:
  log_file: "/home/mailer/log/output.log"

limits:
  mem_min: "50Mi"
  mem_max: "550Mi"
  cpu_min: "100m"
  cpu_max: "500m"

image:
  tag: "a506d73a"
  pullPolicy: Always
  pullSecrets: gitlab

image_A:
  name: 01-mail
  repository: registry.gitlab.com/k8s45/alle_mail/01_mail
  cm: config-01
  secret: token-01
  replicas: 1

image_B:
  name: 02-parser
  repository: registry.gitlab.com/k8s45/alle_mail/02_parser
  cm: config-02
  secret: token-02
  replicas: 1

image_C:
  name: 03-atable
  repository: registry.gitlab.com/k8s45/alle_mail/03_atable
  cm: config-03
  secret: token-03
  replicas: 3

image_D:
  name: 04-status
  repository: registry.gitlab.com/k8s45/alle_mail/04_status
  cm: config-04
  secret: token-04
  replicas: 1
  internal_port: 5000
  external_port: 40054
  health_probe: /health

image_E:
  name: 05-repeater
  cm: config-05
  replicas: 1

image_F:
  name: 06-tracker
  repository: registry.gitlab.com/k8s45/alle_mail/06_tracker
  cm: config-03
  secret: token-03
  schedule: "0 */3 * * *" # every 3 hours
  suspend: false

image_G:
  name: 07-resync
  repository: registry.gitlab.com/k8s45/alle_mail/07_resync
  cm: config-03
  secret: token-03
  schedule: "0 */2 * * *" # every 2 hours
  suspend: false

vault:
  mount_point: "alle_dev"
  common: "common"
  path_01: "mail"
  path_02: null
  path_03: "airtable"
  path_04: null
