apiVersion: v1
kind: Service
metadata:
  name: prometheus-server-np
spec:
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus
  type: NodePort
  ports:
    - name: web
      port: 9090
      targetPort: 9090
      nodePort: 30090

