---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    name: {{ .Values.name }}
spec:
  ports:
    - port: {{ .Values.network.port }}
      targetPort: {{ .Values.network.port }}
      nodePort: {{ .Values.network.external_port }}
  selector:
    app: {{ .Values.name }}
  type: NodePort
