apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 01-auto
spec:
  destination:
    namespace: auto
    server: "https://kubernetes.default.svc"
  source:
    path: example-assets/argocd-apps
    repoURL: https://github.com/loper/argocd.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true


