---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appName }}-np"
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: {{ .Values.service.webPort }}
