---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deimos-config
data:
  TZ: "Europe/Warsaw"
  APP: "{{ .Values.namespace }}"
  DEPLOYMENT: {{ .Values.image_D.name }}
  GIT_USER: "deimos"
  MAX_WAIT: "40"
  NAMESPACE: "{{ .Values.namespace }}"
