---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image_A.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.image_A.name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.image_A.name }}
    spec:
      containers:
        - name: {{ .Values.image_A.name }}
          image: "{{ .Values.image_A.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          tty: true
          envFrom:
            - configMapRef:
                name: {{ .Values.image_A.cm }}
            - secretRef:
                name: {{ .Values.image_A.secret }}
          resources:
            requests:
              memory: {{ .Values.limits.mem_min }}
              cpu: {{ .Values.limits.cpu_min }}
            limits:
              memory: {{ .Values.limits.mem_max }}
              cpu: {{ .Values.limits.cpu_max }}
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            exec:
              command:
                - tail
                - {{ .Values.app.log_file }}
            initialDelaySeconds: 10
            periodSeconds: 55

      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
