---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    name: {{ .Values.name }}
spec:
  ports:
    - port: {{ .Values.image_D.internal_port }}
      targetPort: {{ .Values.image_D.internal_port }}
      nodePort: {{ .Values.image_D.external_port }}
  selector:
    app: {{ .Values.image_D.name }}
  type: NodePort
