---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace }}
data:
  rabbitmqUsername: {{ .Values.secrets.rabbitmqUsername | b64enc }}
  rabbitmqPassword: {{ .Values.secrets.rabbitmqPassword | b64enc }}
