---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.image_F.name }}
spec:
  schedule: "{{ .Values.image_F.schedule }}"
  jobTemplate:
    spec:
      suspend: {{ .Values.image_F.suspend }}
      ttlSecondsAfterFinished: 3000
      template:
        spec:
          containers:
              - name: {{ .Values.image_F.name }}
                image: "{{ .Values.image_F.repository }}:{{ .Values.image.tag }}"
                imagePullPolicy: {{ .Values.image_F.pullPolicy }}
                tty: true
                envFrom:
                  - configMapRef:
                      name: {{ .Values.image_F.cm }}
                  - secretRef:
                      name: {{ .Values.image_F.secret }}
                env:
                  - name: IMAGE_TAG
                    value: {{ .Values.image.tag }}
                resources:
                  requests:
                    memory: {{ .Values.limits.mem_min }}
                    cpu: {{ .Values.limits.cpu_min }}
                  limits:
                    memory: {{ .Values.limits.mem_max }}
                    cpu: {{ .Values.limits.cpu_max }}
                securityContext:
                  allowPrivilegeEscalation: false
                  runAsNonRoot: true
                  runAsUser: 1500
                  runAsGroup: 10500
          nodeSelector:
            kubernetes.io/hostname: "{{ .Values.node_tracker }}"
            
          imagePullSecrets:
            - name: {{ .Values.image.pullSecrets }}
            
          restartPolicy: Never
